name: myapp
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_pdfview: ^1.4.0
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_svg: ^2.0.17
  dotted_border: ^2.1.0
  pdfx: ^2.8.0




flutter:

  uses-material-design: true

  assets:
    - assets/project_x_research.pdf



